create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  enabled boolean not null default true,
  streak integer not null default 0,
  weakest_area text not null default 'Rules of the Road',
  readiness integer not null default 0 check (readiness between 0 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

create policy "Users can read their own push subscriptions"
on public.push_subscriptions for select
to authenticated
using (auth.uid() = user_id);
