create table if not exists public.daily_challenge_results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  challenge_date date not null,
  question_key text not null,
  correct boolean not null default false,
  xp_earned integer not null default 0 check (xp_earned between 0 and 75),
  display_name text not null default 'K53 Learner',
  completed_at timestamptz not null default now(),
  unique (user_id, challenge_date)
);

alter table public.daily_challenge_results enable row level security;

drop policy if exists "Learners can read challenge leaderboard" on public.daily_challenge_results;
create policy "Learners can read challenge leaderboard"
on public.daily_challenge_results for select to authenticated using (true);

drop policy if exists "Learners can submit own daily challenge" on public.daily_challenge_results;
create policy "Learners can submit own daily challenge"
on public.daily_challenge_results for insert to authenticated
with check (auth.uid() = user_id and challenge_date = ((now() at time zone 'Africa/Johannesburg')::date));

create index if not exists daily_challenge_weekly_leaderboard_idx
on public.daily_challenge_results (completed_at desc, xp_earned desc);
