create table if not exists public.referral_codes (
  user_id uuid primary key references auth.users(id) on delete cascade,
  code text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references auth.users(id) on delete cascade,
  referred_id uuid not null unique references auth.users(id) on delete cascade,
  referral_code text not null references public.referral_codes(code),
  status text not null default 'pending' check (status in ('pending','qualified')),
  created_at timestamptz not null default now(),
  qualified_at timestamptz,
  check (referrer_id <> referred_id)
);

alter table public.referral_codes enable row level security;
alter table public.referrals enable row level security;

drop policy if exists "Learners can read own referral code" on public.referral_codes;
create policy "Learners can read own referral code" on public.referral_codes
for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Learners can read own referrals" on public.referrals;
create policy "Learners can read own referrals" on public.referrals
for select to authenticated using (auth.uid() = referrer_id or auth.uid() = referred_id);

create index if not exists referrals_referrer_idx on public.referrals (referrer_id, status);
