import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

const money = (cents) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: "ZAR", maximumFractionDigits: 0 }).format((cents || 0) / 100);
const date = (value) => value ? new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium" }).format(new Date(value)) : "—";

export default function AdminAnalytics({ onQuestions, onBack }) {
  const [data, setData] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [query, setQuery] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); const { data: sessionData } = await supabase.auth.getSession(); const response = await fetch("/api/admin-analytics", { headers: { Authorization: `Bearer ${sessionData.session?.access_token || ""}` } }); const payload = await response.json(); if (!response.ok) setError(payload.error || "Unable to load analytics."); else setData(payload); setLoading(false); }, []);
  useEffect(() => { load(); }, [load]);
  const learners = useMemo(() => (data?.learners || []).filter((item) => item.email?.toLowerCase().includes(query.toLowerCase())), [data, query]);
  const changeAccess = async (learner, action, days) => { const label = action === "cancel" ? `Cancel premium access for ${learner.email}?` : `Add ${days} days of access for ${learner.email}?`; if (!window.confirm(label)) return; setBusy(learner.id); const { data: sessionData } = await supabase.auth.getSession(); const response = await fetch("/api/admin-analytics", { method: "PATCH", headers: { Authorization: `Bearer ${sessionData.session?.access_token || ""}`, "Content-Type": "application/json" }, body: JSON.stringify({ userId: learner.id, action, days }) }); const payload = await response.json(); if (!response.ok) setError(payload.error || "Unable to update access."); else await load(); setBusy(""); };
  const cards = data ? [["Registered learners",data.summary.users],["Active Premium",data.summary.premium],["Free learners",data.summary.free],["Lifetime revenue",money(data.summary.lifetimeRevenueCents)],["Active plan value",money(data.summary.activePlanValueCents)],["Tests completed",data.summary.tests],["Average score",`${data.summary.averageScore}%`],["Pass rate",`${data.summary.passRate}%`]] : [];
  const weakest = data ? Object.entries(data.sectionRates).sort((a,b)=>a[1]-b[1])[0] : null;
  return <div className="analytics-page"><style>{`.analytics-page{min-height:100vh;padding:22px;background:#071812;color:#ecfdf5;font-family:Inter,"Segoe UI",sans-serif}.analytics-shell{max-width:1380px;margin:auto}.analytics-head{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:18px}.analytics-head h1{margin:3px 0 0}.analytics-nav{display:flex;gap:8px}.analytics-btn{border:1px solid #315e50;border-radius:10px;background:#0b2a22;color:#ecfdf5;padding:10px 13px;font-weight:800;cursor:pointer}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.metric,.analytics-card{border:1px solid rgba(110,231,183,.2);border-radius:15px;background:#0a251e;padding:16px}.metric span{display:block;color:#9ed9be;font-size:.7rem;text-transform:uppercase;letter-spacing:.06em}.metric strong{display:block;margin-top:6px;font-size:1.55rem}.analytics-row{display:grid;grid-template-columns:.8fr 1.2fr;gap:12px;margin-top:12px}.analytics-card h2{margin:0 0 13px;font-size:1.05rem}.rate{display:grid;grid-template-columns:150px 1fr 42px;gap:9px;align-items:center;margin:10px 0;font-size:.75rem}.rate-track{height:8px;border-radius:10px;background:rgba(255,255,255,.08);overflow:hidden}.rate-fill{height:100%;background:linear-gradient(90deg,#22c55e,#86efac)}.weak{margin-top:15px;padding:11px;border-radius:10px;background:rgba(250,204,21,.07);color:#fef08a;font-size:.78rem}.learner-card{margin-top:12px}.learner-tools{display:flex;justify-content:space-between;gap:10px;margin-bottom:10px}.learner-tools input{width:min(420px,100%);border:1px solid #315e50;border-radius:10px;background:#071d18;color:#fff;padding:10px}.table-wrap{overflow:auto;max-height:420px}.learners{width:100%;border-collapse:collapse;font-size:.75rem}.learners th,.learners td{padding:9px 8px;text-align:left;border-bottom:1px solid rgba(110,231,183,.12);white-space:nowrap}.learners th{color:#9ed9be}.plan{padding:4px 7px;border-radius:999px;background:rgba(34,197,94,.12);color:#86efac;font-weight:800}.plan.free{background:rgba(148,163,184,.1);color:#cbd5e1}.row-actions{display:flex;gap:5px}.row-actions button{border:1px solid #315e50;border-radius:7px;background:#0c3128;color:#fff;padding:5px 7px;cursor:pointer}.row-actions .cancel{color:#fecaca;border-color:rgba(248,113,113,.25)}.analytics-error{color:#fca5a5}@media(max-width:900px){.metric-grid{grid-template-columns:repeat(2,1fr)}.analytics-row{grid-template-columns:1fr}}@media(max-width:560px){.metric-grid{grid-template-columns:1fr}.analytics-head{align-items:flex-start;flex-direction:column}.rate{grid-template-columns:120px 1fr 40px}}`}</style><div className="analytics-shell"><header className="analytics-head"><div><small>SECURE OWNER TOOL</small><h1>Business Analytics</h1></div><div className="analytics-nav"><button className="analytics-btn" onClick={onQuestions}>Manage Questions</button><button className="analytics-btn" onClick={onBack}>← Dashboard</button></div></header>
  {loading?<p>Loading business data…</p>:error?<p className="analytics-error">{error}</p>:<><section className="metric-grid">{cards.map(([label,value])=><div className="metric" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section><section className="analytics-row"><div className="analytics-card"><h2>Learning performance</h2>{Object.entries(data.sectionRates).map(([label,value])=><div className="rate" key={label}><span>{label}</span><div className="rate-track"><div className="rate-fill" style={{width:`${value}%`}}/></div><b>{value}%</b></div>)}{weakest&&<div className="weak">Weakest category: <strong>{weakest[0]}</strong></div>}</div><div className="analytics-card"><h2>Engagement</h2><div className="metric-grid" style={{gridTemplateColumns:"repeat(3,1fr)"}}><div className="metric"><span>Daily challenges</span><strong>{data.summary.challenges}</strong></div><div className="metric"><span>Mistake practice</span><strong>{data.summary.practices}</strong></div><div className="metric"><span>Tests</span><strong>{data.summary.tests}</strong></div></div></div></section><section className="analytics-card learner-card"><h2>Learner accounts</h2><div className="learner-tools"><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search learner email…"/><span>{learners.length} shown</span></div><div className="table-wrap"><table className="learners"><thead><tr><th>Email</th><th>Plan</th><th>Premium until</th><th>Joined</th><th>Last activity</th><th>Access controls</th></tr></thead><tbody>{learners.map(item=><tr key={item.id}><td>{item.email}</td><td><span className={`plan ${item.plan}`}>{item.plan}</span></td><td>{date(item.premiumUntil)}</td><td>{date(item.createdAt)}</td><td>{date(item.lastActivity)}</td><td><div className="row-actions"><button disabled={busy===item.id} onClick={()=>changeAccess(item,"extend",30)}>+30 days</button><button disabled={busy===item.id} onClick={()=>changeAccess(item,"extend",90)}>+90 days</button>{item.plan!=="free"&&<button className="cancel" disabled={busy===item.id} onClick={()=>changeAccess(item,"cancel")}>Cancel</button>}</div></td></tr>)}</tbody></table></div></section></>}</div></div>;
}
