-- K53 Visual Coach
-- Smart Mistake Practice: per-learner question mastery tracking

create table if not exists public.mistake_question_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  question_key text not null,
  question_text text not null,
  section text,
  attempts integer not null default 0 check (attempts >= 0),
  correct_attempts integer not null default 0 check (correct_attempts >= 0),
  correct_streak integer not null default 0 check (correct_streak >= 0),
  mastered boolean not null default false,
  last_answer_correct boolean,
  last_practiced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, question_key)
);

create index if not exists mistake_question_progress_user_mastered_idx
  on public.mistake_question_progress (user_id, mastered);

alter table public.mistake_question_progress enable row level security;

drop policy if exists "Users can view own mistake question progress"
  on public.mistake_question_progress;

create policy "Users can view own mistake question progress"
on public.mistake_question_progress
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can insert own mistake question progress"
  on public.mistake_question_progress;

create policy "Users can insert own mistake question progress"
on public.mistake_question_progress
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own mistake question progress"
  on public.mistake_question_progress;

create policy "Users can update own mistake question progress"
on public.mistake_question_progress
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own mistake question progress"
  on public.mistake_question_progress;

create policy "Users can delete own mistake question progress"
on public.mistake_question_progress
for delete
to authenticated
using (auth.uid() = user_id);
